version: "3.3"

services:
  app:
    image: digitalocean.com/php
    container_name: app
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www
    networks:
      - app-network

  server:
    image: nginx:alpine
    container_name: server
    ports:
      - "5000:5000"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
