version: "3.3"

services:
  web:
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: ./entrypoint.sh
    ports:
      - 5000:5000
    environment:
      WAIT_HOSTS: db:3306
      docker: "true"
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3606:3606
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
